### ISSUE TITLE
Error on Atom on Jshint package

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#140]
It's a pop up on atom that is saying this:

```
events.js:141
Hide Stack Trace
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:509:16)
    at AtomJsHint.module.exports.AtomJsHint.run (/Users/bryansarnold/.atom/packages/atom-jshint/lib/atom-jshint.js:105:21)
    at AtomJsHint.<anonymous> (/Users/bryansarnold/.atom/packages/atom-jshint/lib/atom-jshint.js:29:16)
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/pane-container.js:346:27
    at Function.module.exports.Emitter.simpleDispatch (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/pane.js:255:22)
    at Pane.module.exports.Pane.activateItem (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/src/pane.js:336:21)
    at atom-tabs.TabBarView.onMouseDown (/opt/homebrew-cask/Caskroom/atom/1.6.0/Atom.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:592:19)
```

**Comment by laurenfazah** [comment]
What is at line 141 in events.js? If it's a function, can you post the whole function? 

Also with the popup closed, are there linter errors? Can you paste those if so?

**Comment by gaand** [comment]
Make sure atom and its packages are up-to-date and then quit and reopen from the command line.

**Comment by ghost** [comment]
Ok...updating it now.

**Comment by ghost** [comment]
done
