### ISSUE TITLE
Annoying last line issue on Atom

### ISSUE THREAD

**Issue by ghost** [ga-wdi-boston/game-project#149]
I'm not sure what's going on. The very last line of my index.js is coming up with this error. I blame the updates:

```
client?cd17:47 ./assets/scripts/index.js
Module build failed: SyntaxError: /Users/bryansarnold/wdi/projects/tic-tac-toe/assets/scripts/index.js: Unexpected token (91:0)

};

    at Parser.pp.raise (/Users/bryansarnold/wdi/projects/tic-tac-toe/node_modules/babel-core/node_modules/babylon/index.js:1378:13)
    at Parser.pp.unexpected (/Users/bryansarnold/wdi/projects/tic-tac-toe/node_modules/babel-core/node_modules/babylon/index.js:2817:8)
    at Parser.pp.parseExprAtom (/Users/bryansarnold/wdi/projects/tic-tac-toe/node_modules/babel-core/node_modules/babylon/index.js:749:12)
    at Parser.pp.parseExprSubscripts (/Users/bryansarnold/wdi/projects/tic-tac-toe/node_modules/babel-core/node_modules/babylon/index.js:504:19)
    at Parser.pp.parseMaybeUnary (/Users/bryansarnold/wdi/projects/tic-tac-toe/node_modules/babel-core/node_modules/babylon/index.js:484:19)
    at Parser.pp.parseExprOps (/Users/bryansarnold/wdi/projects/tic-tac-toe/node_modules/babel-core/node_modules/babylon/index.js:415:19)
    at Parser.pp.parseMaybeConditional (/Users/bryansarnold/wdi/projects/tic-tac-toe/node_modules/babel-core/node_modules/babylon/index.js:397:19)
    at Parser.pp.parseMaybeAssign (/Users/bryansarnold/wdi/projects/tic-tac-toe/node_modules/babel-core/node_modules/babylon/index.js:360:19)
    at Parser.pp.parseExpression (/Users/bryansarnold/wdi/projects/tic-tac-toe/node_modules/babel-core/node_modules/babylon/index.js:324:19)
    at Parser.pp.parseStatement (/Users/bryansarnold/wdi/projects/tic-tac-toe/node_modules/babel-core/node_modules/babylon/index.js:1874:19)
 @ ./index.js 9:0-36onSocketMsg.errors @ client?cd17:47sock.onmessage @ client?cd17:82EventTarget.dispatchEvent @ eventtarget.js:49(anonymous function) @ main.js:274SockJS._transportMessage @ main.js:272EventEmitter.emit @ emitter.js:44WebSocketTransport.ws.onmessage @ websocket.js:35
```

**Comment by gaand** [comment]
This is likely a syntax error.  Does `};` on the last line match an opening curly brace earlier in the file?

**Comment by ghost** [comment]
That was it! You're a brilliant man!
