### ISSUE TITLE
CSS not applying after installing bootstrap.

### ISSUE THREAD

**Issue by kpie89** [ga-wdi-boston/game-project#28]
After installing bootstrap, the following border rules don't apply to my game board. The thing is...the rules apply themselves in on the bottom half of the board but not the top. I can show you this better than explaining it. 

```
.i {
  border-left: 10px solid;
  border-right: 10px solid;
}

.j {
  border-bottom: 10px solid;
  border-top: 10px solid;
}
```

**Comment by GA-MEB** [comment]
Bootstrap table styling apparently has higher specificity than those selectors. Recommending that you use `div`s instead of a table.

**Comment by kpie89** [comment]
https://bootstrapbay.com/blog/customize-bootstrap/

This website has me create a custom scss file to override certain bootstrap stylings. BOY WOULD I LOVE THAT. 

But when I try I get this error message: 

```
Error: rbenv: version `2.2.2' is not installed (set by /Users/kevinpie/wdi/projects/tic-tac/ticky-tacky/node_modules/bootstrap-sass/.ruby-version)
Error: rbenv: version `2.2.2' is not installed (set by /Users/kevinpie/wdi/projects/tic-tac/ticky-tacky/node_modules/bootstrap-sass/.ruby-version)
    at parameters.exit (/Users/kevinpie/.atom/packages/linter-ruby/node_modules/atom-linter/lib/helpers.js:75:20)
    at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.4.0/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

Also it won't seem to let me create the file within the bootstrap folder itself. Only within the mix-ins subfolder within that folder.

**Comment by RealWeeks** [comment]
Look into "!important" to override certain stylings.
