### ISSUE TITLE
console error  -- whaaaat?

### ISSUE THREAD

**Issue by RpRoderick** [ga-wdi-boston/game-project#351]
```bash
TypeError: Cannot read property 'then' of undefined at HTMLButtonElement.onCreateGame (http://localhost:7165/bundle.js:726:20) at HTMLButtonElement.dispatch (http://localhost:7165/vendor.bundle.js:5311:28) at HTMLButtonElement.elemData.handle (http://localhost:7165/vendor.bundle.js:5119:29)
message
:
"Cannot read property 'then' of undefined"
stack
:
"TypeError: Cannot read property 'then' of undefined↵    at HTMLButtonElement.onCreateGame (http://localhost:7165/bundle.js:726:20)↵    at HTMLButtonElement.dispatch (http://localhost:7165/vendor.bundle.js:5311:28)↵    at HTMLButtonElement.elemData.handle (http://localhost:7165/vendor.bundle.js:5119:29)"
__proto__
:
Error
```

**Comment by raq929** [comment]
Looks like there's an error with one of your Ajax requests.

**Comment by raq929** [comment]
Can you post that file?

**Comment by RpRoderick** [comment]
``` js
'use strict';

// const config = require('../config.js');
const store = require('../scripts/store.js');


  const createGame = function () {
    $.ajax({
      url: store.host + '/games',
      method: 'POST',
      headers: {
        Authorization: 'Token token=' + store.user.token,
      },
      game: {}
    });
    };
```

**Comment by RpRoderick** [comment]
saying that createGame is undefined...

`const onCreateGame = function (event) {
  debugger;
  event.preventDefault();
  api.createGame()
    .then(ui.success)
    .catch(ui.failure);
};`

**Comment by RpRoderick** [comment]
``` js
const onCreateGame = function (event) {
  debugger;
  event.preventDefault();
  api.createGame()
    .then(ui.success)
    .catch(ui.failure);
};
```

**Comment by RpRoderick** [comment]
I think.  Not sure

**Comment by neugierige** [comment]
let me take a look

**Comment by raq929** [comment]
Did you put createGame in your exports?

**Comment by RpRoderick** [comment]
yes

**Comment by RealWeeks** [comment]
```js
const onCreateGame = function (event) { 
debugger; 
event.preventDefault(); 
api.createGame() .then(ui.success) .catch(ui.failure);
 };
```

this is incorrect syntax

**Comment by RpRoderick** [comment]
how so?  It was copied from the other api.  I'll check it against kevin's

**Comment by RealWeeks** [comment]
Deleted my comment, syntax is correct

**Comment by RpRoderick** [comment]
ok

**Comment by RealWeeks** [comment]
I'm gonna take a look at this

**Comment by RpRoderick** [comment]
Ok, for anyone looking at this in the future, issue was that I did not have a Return before the AJAX call.  correct code is below, compare to code above:

`const createGame = function () {
    return $.ajax({
      url: store.host + '/games',
      method: 'POST',
      headers: {
        Authorization: 'Token token=' + store.user.token,
      },
      game: {}
    });
    };`
