### ISSUE TITLE
node error

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#419]
I am getting an error in node when i try to test my game engine.

Error message:
```
> const f = require('./assets/scripts/index.js')
ReferenceError: $ is not defined
    at Object.<anonymous> (/Users/MD/wdi/projects/tic-tac-toe/assets/scripts/index.js:6:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at repl:1:11
    at sigintHandlersWrap (vm.js:22:35)
```

code in my file:
```
'use strict';

const setAPIOrigin = require('../../lib/set-api-origin');
const config = require('./config');

$(() => {
  setAPIOrigin(location, config);
});

// use require with a reference to bundle the file and use it in this file
// const example = require('./example');
// use require without a reference to ensure a file is bundled
const userEvents = require('./Auth/events');

// On Document ready
$(() => {
  $('#user-destroy').on('submit', userEvents.onDeleteUser);
  $('#edit-user').on('submit', userEvents.onPatchUser);
  $('#add-user').on('submit', userEvents.onPostUser);
});

// GAME ENGINE
$(document).ready(function () {
  const gameBoard = function () {
//rest of code continues...
```

The problem is that the first dollar character is not defined. if i comment it out, then the next dollar character is not defined and so on and so forth. 
How to I get my file to understand there is jquery in the file? i believe that by doing so it would then recognize that character and will finally let me test my code in node.

**Comment by bernardlee** [comment]
Where is your game logic located and can you paste the contents of that file?

**Comment by doremaxime** [comment]
Absolutly, here is the rest of the code: 
```
'use strict';

const setAPIOrigin = require('../../lib/set-api-origin');
const config = require('./config');

$(() => {
  setAPIOrigin(location, config);
});

// use require with a reference to bundle the file and use it in this file
// const example = require('./example');

// use require without a reference to ensure a file is bundled
const userEvents = require('./Auth/events');

// On Document ready
$(() => {
  $('#user-destroy').on('submit', userEvents.onDeleteUser);
  $('#edit-user').on('submit', userEvents.onPatchUser);
  $('#add-user').on('submit', userEvents.onPostUser);
});




// GAME ENGINE

// COMMIT!

// When the document has been loaded...
$(document).ready(function () {
  const gameBoard = function () {

    // first turn starts at 0 which will make the first turn X
    let turn = 0;

    // All circles blank
    $('.circles').html('');

    // isGameOver method
    function isGameOver() {
      // 3 X's in a row.
      if ((($('#TL') === 'X') && ($('#TC') === 'X') && ($('#TR') === 'X')) ||
        (($('#ML') === 'X') && ($('#MC') === 'X') && ($('#MR') === 'X')) ||
        (($('#BL') === 'X') && ($('#BC') === 'X') && ($('#BR') === 'X')) ||
        (($('#TL') === 'X') && ($('#MC') === 'X') && ($('#BR') === 'X')) ||
        (($('#BL') === 'X') && ($('#MC') === 'X') && ($('#TR') === 'X'))) {
        $('.messageX').show();
        setTimeout(function () { $('.messageX').hide(); }, 5000);
      } else if ((($('#TL') === 'O') && ($('#TC') === 'O') && ($('#TR') === 'O')) ||
          (($('#ML') === 'O') && ($('#MC') === 'O') && ($('#MR') === 'O')) ||
          (($('#BL') === 'O') && ($('#BC') === 'O') && ($('#BR') === 'O')) ||
          (($('#TL') === 'O') && ($('#MC') === 'O') && ($('#BR') === 'O')) ||
          (($('#BL') === 'O') && ($('#MC') === 'O') && ($('#TR') === 'O'))) {
        $('.messageO').show();
        setTimeout(function () { $('.messageO').hide(); }, 5000);
      } else if (turn === 8) {

        // none of the above plus board full (if one of the above is valid,
        // does the method stop there? need to include if turn is 8?)
        $('.messageTie').show();

        // http://stackoverflow.com/questions/3428766/jquery-show-for-5-seconds-then-hide
        setTimeout(function () { $('.messageTie').hide(); }, 5000);

      }
    } // need to create messages

    // addSymbol:
    $('.circle').on('click', function () {
      if ($(this).html() === '') {
        if (turn % 2 === 0) {
          // if it's divisable then it's got to be the first player who is X
          $(this).html('X');
        } else {
          // if it's NOT divisable then it's got to be the second player who is O
          $(this).html('O');
        }

        // When clicked, THAT button is deactivated. (So as to NOT be clicked again to be O or X again)
        // and will in turn will make the game not be playable once it's over.
        $(this).prop('disabled', true); //http://api.jquery.com/prop/

        //check to see if winner or tie
        isGameOver();

        // add turn for next player
        turn++;

      }

    });

    // restart
    // If .restart is clicked, run gameBoard function?.
    $('.restart').on('click', function () {

      //resets the counter so that x starts.
      turn = 0;

      // can I run a function inside that function?
      gameBoard();

    });

  };

  gameBoard();

});
```

**Comment by bernardlee** [comment]
This is needlessly complicated and will be extremely difficult to maintain and update.  You should have your game logic in plain JavaScript (e.g., manipulating an array that represents the game state, methods that check for win conditions, etc.) and your jQuery calls should be the interface between the game logic and the user interacting with the page.

**Comment by doremaxime** [comment]
When Jeff explains it on the board it makes sense but I don't know how to code it with the array way and indexes so I am trying with whatever I can come up with.. 
I also don't understand why my jquery currently isn't the interface between the game logic and the user interacting with the page. A user interacts with the site by clicking which affects the logic no?

**Comment by bernardlee** [comment]
Try drawing it out on paper or use any of the whiteboards here and it will probably help.  Right now you are essentially implementing the game logic using jQuery.  What you should do is represent the game state and logic using plain JavaScript and use jQuery to, say, detect clicks and call methods related to game state manipulation.  e.g., you have an array that represents the board, a `setToken(arrayIndex, token)` method that puts player tokens on the board (array), a click handler (using jQuery) that calls `setToken(...)`, and then a way to check the game state (array) and populate the displayed grid with the appropriate player tokens.

**Comment by doremaxime** [comment]
Thanks, I also remember your slack post: https://ga-students.slack.com/files/bernard/F3VPH3N12/js-boggle-challenge.js
However, for some reason I'm not understanding the functionality it seems like everyone is.
I tried drawing it out a couple times but i'll try again.

**Comment by bernardlee** [comment]
This might help.  Try writing the game logic in such a way that you can do something like this (this is incomplete code with no implementations, just to give you an idea of how it might work):

```javascript
// Make a new 9-element array and set every element to an empty string.
const gameBoard = new Array(9).fill('');

// This example function takes an array index and a player token as arguments.
setToken(3, 'X');
console.log(gameBoard); // ['', '', '', 'X', '', '', '', '', '']
setToken(0, 'O');
console.log(gameBoard); // ['O', '', '', 'X', '', '', '', '', '']
// etc.
```

**Comment by jrhorn424** [comment]
> How to I get my file to understand there is jquery in the file? i believe that by doing so it would then recognize that character and will finally let me test my code in node.

I just wanted to pop in and say that @bernardlee is giving good advice and leading you down the right track. But the answer to your original question is that you can't use jQuery in `node` because there is no DOM in the terminal.

So when I say, "test your engine in `node`", there is an implicit assumption that your engine does not use jQuery.
