### ISSUE TITLE
Node error message

### ISSUE THREAD

**Issue by doremaxime** [ga-wdi-boston/game-project#440]
I am trying to test my engine in node but getting an error message:

```
> const o = require('./assets/scripts/gameEngine.js');
undefined
> o.setToken();
TypeError: o.setToken is not a function
    at repl:1:3
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
> o.setToken
undefined
> o.setToken(3,'x')
TypeError: o.setToken is not a function
    at repl:1:3
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:545:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
> o.setToken(3,'x');
TypeError: o.setToken is not a function
```

The error, saying that setToken is not a function, confuses me because it has all the components of a function.

here it is in my gameEngine.js 
```
// inserts token into array.
const setToken = function (a, b) {
  // a = the index, b = the token we insert.
  gameBoard.splice(a, 0, b);
  // check for a winner/tie.
  checkWinner();
};

module.exports = {
  setToken,
  checkEachIndex,
  checkWinner,
};

// This example function takes an array index and a player token as arguments.
// setToken(3, 'X');
// console.log(gameBoard); // ['', '', '', 'X', '', '', '', '', '']
// setToken(0, 'O');
// console.log(gameBoard); // ['O', '', '', 'X', '', '', '', '', '']
```

I expected to be able to test this function but cannot.

Furthermore, it is now Thursday night and the fact that I have restarted 3 times and have nothing to show is becoming a serious concern...

**Comment by bernardlee** [comment]
Can you update your repository so that I can see everything that you have?

**Comment by doremaxime** [comment]
i have pushed my feature branch.

**Comment by bernardlee** [comment]
Have you tried it again since then?  I just cloned your repository, checked out the feature branch, ran node, used the same commands that you did, but didn't get any errors.

```
> const o = require('./assets/scripts/gameEngine');
undefined
> o
{ setToken: [Function: setToken],
  checkEachIndex: [Function: checkEachIndex],
  checkWinner: [Function: checkWinner] }
> o.setToken();
undefined
> o.setToken
[Function: setToken]
> o.setToken(3, 'x');
undefined
```

**Comment by doremaxime** [comment]
I found my error, i had .js at the end.

I ran: 
> const o = require('./assets/scripts/gameEngine.js');

whereas you ran:
> const o = require('./assets/scripts/gameEngine');

Thank you Bernard!

**Comment by bernardlee** [comment]
That's odd.  It should still work with `.js`.  I just tried it.

```
> const o = require('./assets/scripts/gameEngine.js')
undefined
> o
{ setToken: [Function: setToken],
  checkEachIndex: [Function: checkEachIndex],
  checkWinner: [Function: checkWinner] }
```

**Comment by doremaxime** [comment]
I restarted my terminal and it now works with .js as well!

**Comment by jrhorn424** [comment]
Sounds like you may have been testing an old version of your engine. Every time you modify and save a file you've imported into `node`, you have to restart `node` and import again. Good work solving this!
