### ISSUE TITLE
Error trying to create a new game via curl request

### ISSUE THREAD

**Issue by danielleletarte** [ga-wdi-boston/game-project#511]
Attempting to create a new game via a curl request. I am passing just the token for a signed in player via terminal. I get the below error message. My path appears to be correct, so not sure why the route is not found. I made sure to exclude the body and have checked my syntax against past examples.

``` js
#TOKEN=BAhJIiVlYmFjNWY3ZjlmMmUyOGI5ZjEzZWZhNDZkMmZkZTdkMwY6BkVG--cad6000f8aee36d9a5ad3485cbc6643a1505fdba sh scripts/game/create-game.sh

API="${API_ORIGIN:-http://localhost:4741}"
  URL_PATH="/games"
  curl "${API}${URL_PATH}" \
    --include \
    --request POST \
    --header "Authorization: Token token=$TOKEN"
```
![image](https://cloud.githubusercontent.com/assets/25553014/24724474/3fabba3e-1a19-11e7-8065-ffa4a743ede8.png)

**Comment by jordanallain** [comment]
Read it over very carefully and make sure it is structured correctly.

**Comment by BenGitsCode** [comment]
Please use code blocks like [this](https://help.github.com/articles/creating-and-highlighting-code-blocks/)

There might be some helpful errors to search for in that screenshot, but I can't copy text from images.

Don't worry if it's huge, we ❤️ errors.

**Comment by danielleletarte** [comment]
Got it. Didn't think to use this format with terminal errors.

```
HTTP/1.1 404 Not Found
Content-Type: application/json; charset=utf-8
X-Request-Id: 795f486f-b675-4294-a990-a524db3fe578
X-Runtime: 0.006991
Vary: Origin
Content-Length: 3767

{"status":404,"error":"Not Found","exception":"#\u003cActionController::RoutingError: No route matches [POST] \"/games\"\u003e","traces":{"Application Trace":[],"Framework Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'"},{"id":1,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":2,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":3,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":4,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'"},{"id":5,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":6,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'"},{"id":7,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'"},{"id":8,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'"},{"id":9,"trace":"rack (2.0.1) lib/rack/runtime.rb:22:in `call'"},{"id":10,"trace":"activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"},{"id":11,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":12,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'"},{"id":13,"trace":"rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"},{"id":14,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":15,"trace":"railties (5.0.1) lib/rails/engine.rb:522:in `call'"},{"id":16,"trace":"puma (3.7.0) lib/puma/configuration.rb:226:in `call'"},{"id":17,"trace":"puma (3.7.0) lib/puma/server.rb:578:in `handle_request'"},{"id":18,"trace":"puma (3.7.0) lib/puma/server.rb:415:in `process_client'"},{"id":19,"trace":"puma (3.7.0) lib/puma/server.rb:275:in `block in run'"},{"id":20,"trace":"puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"}],"Full Trace":[{"id":0,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:53:in `call'"},{"id":1,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"},{"id":2,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:36:in `call_app'"},{"id":3,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `block in call'"},{"id":4,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'"},{"id":5,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'"},{"id":6,"trace":"activesupport (5.0.1) lib/active_support/tagged_logging.rb:69:in `tagged'"},{"id":7,"trace":"railties (5.0.1) lib/rails/rack/logger.rb:24:in `call'"},{"id":8,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'"},{"id":9,"trace":"rack (2.0.1) lib/rack/runtime.rb:22:in `call'"},{"id":10,"trace":"activesupport (5.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'"},{"id":11,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'"},{"id":12,"trace":"actionpack (5.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'"},{"id":13,"trace":"rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"},{"id":14,"trace":"rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'"},{"id":15,"trace":"railties (5.0.1) lib/rails/engine.rb:522:in `call'"},{"id":16,"trace":"puma (3.7.0) lib/puma/configuration.rb:226:in `call'"},{"id":17,"trace":"puma (3.7.0) lib/puma/server.rb:578:in `handle_request'"},{"id":18,"trace":"puma (3.7.0) lib/puma/server.rb:415:in `process_client'"},{"id":19,"trace":"puma (3.7.0) lib/puma/server.rb:275:in `block in run'"},{"id":20,"trace":"puma (3.7.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"}]}}
```

**Comment by danman01** [comment]
You are getting a `404 not found`, and looking deeper into the error text, it tells you 
```
No route matches \"/games\"\u003e"
```
Make sure whatever you are triggering the `POST` with is sending the data to the correct endpoint, so for users, `POST`ing to `/users` is what you want. It should be similar for games.

**Comment by danielleletarte** [comment]
In the game API guide it indicates the POST should go to URI "/games". I have compared my code with my neighbor and everything looks exactly the same, but I get an error with each attempt to run it.

**Comment by danman01** [comment]
Just a guess, but I think there may be a syntax error somewhere around the URL, resulting in the appending of `\u003e` to the url you want: http://stackoverflow.com/questions/4858494/what-does-u003c-mean

**Comment by danielleletarte** [comment]
I have also tried cut/pasting code that is working for another team member directly into terminal with no luck. I still get the same error. I took what Sam posted in Slack and added the token of a signed in user for my app.

```
curl --include --request POST http://localhost:4741/games \
--header "Authorization: Token token=4ae6610c008d55e8162f2d329398efcd" \
--data-urlencode ""
```

**Comment by danielleletarte** [comment]
After some googling I did "bundle exec rake routes" from the directory I have been launching rails and got the following

```
$ bundle exec rake routes
  Prefix Verb   URI Pattern                    Controller#Action
examples GET    /examples(.:format)            examples#index
         POST   /examples(.:format)            examples#create
 example GET    /examples/:id(.:format)        examples#show
         PATCH  /examples/:id(.:format)        examples#update
         PUT    /examples/:id(.:format)        examples#update
         DELETE /examples/:id(.:format)        examples#destroy
 sign_up POST   /sign-up(.:format)             users#signup
 sign_in POST   /sign-in(.:format)             users#signin
         DELETE /sign-out/:id(.:format)        users#signout
         PATCH  /change-password/:id(.:format) users#changepw
   users GET    /users(.:format)               users#index
    user GET    /users/:id(.:format)           users#show
   books GET    /books(.:format)               books#index
         POST   /books(.:format)               books#create
    book GET    /books/:id(.:format)           books#show
         PATCH  /books/:id(.:format)           books#update
         PUT    /books/:id(.:format)           books#update
         DELETE /books/:id(.:format)           books#destroy
```

This is the old books API we used in class and the the one we used for the authentication exercises. So I guess my question is, where should I be launching rails from? I must have missed something..

**Comment by jordanallain** [comment]
sounds like you aren't hitting the API you want to be hitting. do you have the game-project-api cloned locally?

**Comment by danielleletarte** [comment]
YES! Forgot we did that the other day. Just realized it now. Thank you!
