### ISSUE TITLE
Running into a wall trying to pass a click function to my game board!

### ISSUE THREAD

**Issue by Azinck94** [ga-wdi-boston/game-project#776]
Hi I am trying to create a jquery function for my game board but I am getting grunt serve errors from it, wondering if anyone could help point me in the right direction to how I could learn to fix it!

This is my Index.js

'use strict'
require('./assets/scripts/index.js')

// styles
require('./assets/styles/index.scss')
$(document).ready(function(){
    var turnCount=0;

      $('#game-board').find('#game-cell').on('click', function(){
            if (turnCount % 2 === 0){
              $(this).text('X');
              checkVictory('X');
            } else {
           //player 2's turn (O)
              $(this).text('O');
              checkVictory('O');
            }
          turnCount++;

      });
    }

I can show my gameboard as well if necessary.

**Comment by jordanallain** [comment]
can you post the error from your server?

**Comment by Azinck94** [comment]
parsing error: Unexpected token (fatal)

**Comment by jordanallain** [comment]
does it give you a file/line number/character number?

**Comment by jordanallain** [comment]
looks like you are missing a closing paren

**Comment by Azinck94** [comment]
line 22:1, but its kinda bugging out no matter what I do unless I comment the whole thing out. When I added a paren everything went red haha 
``
`

**Comment by jordanallain** [comment]
where did you add the paren?

**Comment by jordanallain** [comment]
```
$(document).ready(function(){
                 ^
```

thats the one that isn't being closed

**Comment by Azinck94** [comment]
require('./assets/scripts/index.js')

// styles
require('./assets/styles/index.scss')
$(document).ready(function(){
    var turnCount = 0

      $('#game-board').find('#game-cell').on('click', function(){
            if (turnCount % 2 === 0){
              $(this).text('X');
              checkVictory('X');
            } else {
           //player 2's turn (O)
              $(this).text('O');
              checkVictory('O');
            }
          turnCount++;

      }
    })
  ) 
its still yelling at me saying "unexpected token {"

**Comment by jordanallain** [comment]
Take it slow. Isolate each line at a time, make sure each opening character has a matching closing one. You can do it!

**Comment by Azinck94** [comment]
Will do thanks, other than that I'm having a big issue when trying to run my ajax signUp stuff, my grunt gives me the following error ERROR in ./assets/scripts/signup.sh
Module parse failed: /Users/firstuser/wdi/projects/browser-template/assets/scripts/signup.sh Unexpected token (1:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:5)
    at Parser.pp$4.raise (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseTopLevel (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/firstuser/wdi/projects/browser-template/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/Users/firstuser/wdi/projects/browser-template/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (/Users/firstuser/wdi/projects/browser-template/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at DependenciesBlock.onLoadPitchDone (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
    at DependenciesBlock.loadPitch (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at DependenciesBlock.doBuild (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/Compilation.js:126:9)
    at /Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/Compilation.js:309:10
    at /Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModuleFactory.js:58:13
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/firstuser/wdi/projects/browser-template/node_modules/tapable/lib/Tapable.js:75:69)
    at onDoneResolving (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModuleFactory.js:38:11)
    at onDoneResolving (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModuleFactory.js:121:6)
    at /Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModuleFactory.js:116:7
    at /Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:726:13
    at /Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:236:30)
    at _parallel (/Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:731:9)
    at /Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModuleFactory.js:109:12
    at /Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:726:13
    at /Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:52:16
    at async.forEachOf.async.eachOf (/Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:236:30)
    at _parallel (/Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:731:9)
    at /Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModuleFactory.js:75:10
    at /Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModuleFactory.js:28:4
    at /Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModuleFactory.js:159:3
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/firstuser/wdi/projects/browser-template/node_modules/tapable/lib/Tapable.js:75:69)
    at NormalModuleFactory.create (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/NormalModuleFactory.js:144:8)
    at /Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/Compilation.js:214:11
    at /Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/firstuser/wdi/projects/browser-template/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/Compilation.js:185:8)
    at Compilation.processModuleDependencies (/Users/firstuser/wdi/projects/browser-template/node_modules/webpack/lib/Compilation.js:170:7)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./index.js 7:0-37


which I don't understand at all, could I sit down with someone tomorrow am to quickly review what the problem could be? Appreciate the help Jordan!

**Comment by jordanallain** [comment]
You likely just have a syntax error that is causing other things to error along the way, don't worry it's not as bad as that output looks. 

If you are still stuck on this issue tomorrow morning we can set up a 1on1

**Comment by Azinck94** [comment]
great thanks!

**Comment by jordanallain** [comment]
@Azinck94 what's the current state, still on the same error here?

**Comment by Azinck94** [comment]
I commented out the require file paths that were causing it to bug out, am going to restart the Authorization process from scratch
